CREATE WAREHOUSE IF NOT EXISTS NORTHLAKE_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  COMMENT = 'Compute warehouse for Northlake HQ analytics project';

USE WAREHOUSE NORTHLAKE_WH;