CREATE OR REPLACE FILE FORMAT NORTHLAKE_DB.RAW.CSV_FORMAT
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('NULL', 'null', 'N/A', '') 
  DATE_FORMAT ='YYYY-MM-DD'
  TIMESTAMP_FORMAT ='YYYY-MM-DD HH24:MI:SS';